// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A product recommendation AI agent.
 *
 * - productRecommendations - A function that handles the product recommendation process.
 * - ProductRecommendationsInput - The input type for the productRecommendations function.
 * - ProductRecommendationsOutput - The return type for the productRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ProductSchema = z.object({
  name: z.string().describe('The name of the product.'),
  category: z.string().describe('The category of the product.'),
  description: z.string().describe('A short description of the product.'),
});

const ProductRecommendationsInputSchema = z.object({
  cartItems: z
    .array(ProductSchema)
    .describe('The list of products currently in the user\'s cart.'),
});
export type ProductRecommendationsInput = z.infer<
  typeof ProductRecommendationsInputSchema
>;

const ProductRecommendationsOutputSchema = z.array(ProductSchema);
export type ProductRecommendationsOutput = z.infer<
  typeof ProductRecommendationsOutputSchema
>;

export async function productRecommendations(
  input: ProductRecommendationsInput
): Promise<ProductRecommendationsOutput> {
  return productRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'productRecommendationsPrompt',
  input: {schema: ProductRecommendationsInputSchema},
  output: {schema: ProductRecommendationsOutputSchema},
  prompt: `You are an AI assistant specializing in product recommendations for an e-commerce store.

  Based on the items currently in the user\'s cart, suggest related or complementary products that the user might be interested in purchasing.

  The products in the cart are:
  {{#each cartItems}}
  - {{this.name}} (Category: {{this.category}}, Description: {{this.description}})
  {{/each}}

  Please provide a list of products with their names, categories and descriptions that would complement the items in the cart.
  Ensure that the recommendations are relevant and enhance the user\'s shopping experience.
  Format the response as a JSON array of products.`,
});

const productRecommendationsFlow = ai.defineFlow(
  {
    name: 'productRecommendationsFlow',
    inputSchema: ProductRecommendationsInputSchema,
    outputSchema: ProductRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
